import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';import {demoRepository} from '../demo/repository';import {api} from '../api/client';import {createDemo} from '../demo/data';import {getSettings,setSettings} from '../persistence/db';import type {AppSettings,DemoData,Scenario} from '../domain/models';
type Context={settings:AppSettings;data?:DemoData;loading:boolean;error?:string;refresh:()=>Promise<void>;patch:(v:Partial<AppSettings>)=>Promise<void>;setScenario:(v:Scenario)=>Promise<void>;reset:()=>Promise<void>};
const C=createContext<Context|null>(null);export const dataMode=((import.meta.env.VITE_DATA_MODE as string|undefined)??'demo') as 'demo'|'api';
export function AppProvider({children}:{children:ReactNode}){const [settingsState,setSettingsState]=useState<AppSettings>();const [data,setData]=useState<DemoData>();const [loading,setLoading]=useState(true);const [error,setError]=useState<string>();const settings=settingsState??({theme:'system',language:'ru',demoOffline:false,demoError:false,scenario:'normal',entered:false} satisfies AppSettings);
const refresh=async()=>{setLoading(true);setError(undefined);try{if(dataMode==='demo')setData(await demoRepository.data(settings.demoError,settings.demoOffline));else{const [plan,explanation,debts,transactions]=await Promise.all([api.plan(),api.explanation(),api.debts(),api.transactions()]);const shell=createDemo('empty');setData({...shell,plan,explanation,debts,transactions,currency:plan.currency,updatedAt:new Date().toISOString()})}}catch(e){setError((e as Error).message)}finally{setLoading(false)}};
useEffect(()=>{void getSettings().then(async v=>{setSettingsState(v);if(dataMode==='demo')setData(await demoRepository.data(false,v.demoOffline));else{const [plan,explanation,debts,transactions]=await Promise.all([api.plan(),api.explanation(),api.debts(),api.transactions()]);const shell=createDemo('empty');setData({...shell,plan,explanation,debts,transactions,currency:plan.currency,updatedAt:new Date().toISOString()})}}).catch(e=>setError((e as Error).message)).finally(()=>setLoading(false))},[]);
useEffect(()=>{const dark=settings.theme==='dark'||(settings.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light';document.documentElement.lang=settings.language},[settings.theme,settings.language]);
useEffect(()=>{const online=()=>{if(!settings.demoOffline)void demoRepository.sync().then(refresh)};addEventListener('online',online);return()=>removeEventListener('online',online)},[settings.demoOffline]);
const patch=async(v:Partial<AppSettings>)=>{const next={...settings,...v};setSettingsState(next);await setSettings(next)};const setScenario=async(s:Scenario)=>{await patch({scenario:s});setData(await demoRepository.scenario(s))};const reset=async()=>{await demoRepository.reset();await patch({scenario:'normal',demoOffline:false,demoError:false});await refresh()};
return <C.Provider value={{settings,data,loading,error,refresh,patch,setScenario,reset}}>{children}</C.Provider>};export function useApp(){const v=useContext(C);if(!v)throw new Error('AppProvider missing');return v}
