import {createDemo} from './data'; import {db,getDemo,setDemo} from '../persistence/db'; import type {Debt,DemoData,QueuedMutation,Scenario,Transaction} from '../domain/models'; import {newId,stableKey} from '../domain/money';
const sleep=(ms=260)=>new Promise(r=>setTimeout(r,ms));
export class DemoRepository {async data(error=false,offline=false){await sleep();if(error)throw new Error('Искусственная ошибка demo');let value=await getDemo();if(!value){value=createDemo();await setDemo(value)}if(offline&&!value)throw new Error('offline');return value} async scenario(s:Scenario){const value=createDemo(s);await setDemo(value);return value} async reset(){await setDemo(createDemo())}
async queue(kind:QueuedMutation['kind'],entityId:string,payload:unknown){const existing=await db.queue.where('entityId').equals(entityId).and(x=>x.kind===kind&&x.status!=='synced').first();if(existing)return existing;const q:QueuedMutation={id:newId(),kind,entityId,payload,idempotencyKey:stableKey(kind,entityId),status:'pending',attempts:0,nextAttemptAt:Date.now(),createdAt:Date.now()};await db.queue.put(q);return q}
async addTransaction(input:Omit<Transaction,'id'|'syncStatus'>,offline:boolean){const data=(await getDemo())??createDemo();const item:Transaction={...input,id:newId(),syncStatus:offline?'pending':'synced'};data.transactions.unshift(item);data.updatedAt=new Date().toISOString();await setDemo(data);await this.queue('transaction.create',item.id,item);if(!offline)await this.sync();return item}
async deleteTransaction(id:string){const data=(await getDemo())??createDemo();data.transactions=data.transactions.filter(x=>x.id!==id);await setDemo(data)}
async saveDebt(input:Omit<Debt,'id'|'syncStatus'>,id:string|undefined,offline:boolean){const data=(await getDemo())??createDemo();const item:Debt={...input,id:id??newId(),syncStatus:offline?'pending':'synced'};const index=data.debts.findIndex(x=>x.id===item.id);if(index<0)data.debts.push(item);else data.debts[index]=item;await setDemo(data);await this.queue(id?'debt.update':'debt.create',item.id,item);if(!offline)await this.sync();return item}
async deleteDebt(id:string,offline:boolean){const data=(await getDemo())??createDemo();data.debts=data.debts.filter(x=>x.id!==id);await setDemo(data);await this.queue('debt.delete',id,undefined);if(!offline)await this.sync()}
async sync(forceFailure=false){const all=await db.queue.where('status').anyOf('pending','failed').sortBy('createdAt');for(const q of all){if(q.nextAttemptAt>Date.now())continue;if(forceFailure){q.attempts++;q.status=q.attempts>=3?'failed':'pending';q.nextAttemptAt=Date.now()+Math.min(30000,500*2**q.attempts);q.error='Нет связи';await db.queue.put(q);continue}q.status='synced';q.error=undefined;await db.queue.put(q);const data=await getDemo();if(data){data.transactions=data.transactions.map(x=>x.id===q.entityId?{...x,syncStatus:'synced'}:x);data.debts=data.debts.map(x=>x.id===q.entityId?{...x,syncStatus:'synced'}:x);data.updatedAt=new Date().toISOString();await setDemo(data)}}}
async queueStats(){const values=await db.queue.toArray();return {pending:values.filter(x=>x.status==='pending').length,failed:values.filter(x=>x.status==='failed'||x.status==='conflict').length,total:values.length}}
}
export const demoRepository=new DemoRepository();
