class IncomeDraft { IncomeDraft({this.name='Доход',this.amount=0,required this.date,this.confirmed=true}); factory IncomeDraft.fromJson(Map<String,dynamic> j)=>IncomeDraft(name:j['name'] as String,amount:j['amount'] as int,date:DateTime.parse(j['due_date'] as String),confirmed:j['confirmed'] as bool? ?? true); String name; int amount; DateTime date; bool confirmed; Map<String,dynamic> toJson()=>{'name':name,'amount':amount,'due_date':date.toIso8601String().substring(0,10),'confirmed':confirmed}; }
class ExpenseDraft { ExpenseDraft({this.name='Расход',this.amount=0,required this.date}); factory ExpenseDraft.fromJson(Map<String,dynamic> j)=>ExpenseDraft(name:j['name'] as String,amount:j['amount'] as int,date:DateTime.parse(j['due_date'] as String)); String name; int amount; DateTime date; Map<String,dynamic> toJson()=>{'name':name,'amount':amount,'due_date':date.toIso8601String().substring(0,10)}; }
class DebtDraft { DebtDraft({this.name='Долг',this.balance=0,this.rateBps=0,this.minimum=0,this.dueDay=15}); factory DebtDraft.fromJson(Map<String,dynamic> j)=>DebtDraft(name:j['name'] as String,balance:j['balance'] as int,rateBps:j['annual_rate_bps'] as int,minimum:j['minimum_payment'] as int,dueDay:j['due_day'] as int); String name; int balance,rateBps,minimum,dueDay; Map<String,dynamic> toJson()=>{'name':name,'balance':balance,'annual_rate_bps':rateBps,'minimum_payment':minimum,'due_day':dueDay}; }
class OnboardingDraft {
  String currency='RUB'; int available=0, reserve=0, step=0;
  final incomes=<IncomeDraft>[], expenses=<ExpenseDraft>[], debts=<DebtDraft>[];
  Map<String,dynamic> payload()=>{'language':'ru','currency':currency,'available_now':available,'minimum_buffer':reserve,'incomes':incomes.map((e)=>e.toJson()).toList(),'expenses':expenses.map((e)=>e.toJson()).toList(),'debts':debts.map((e)=>e.toJson()).toList()};
  Map<String,dynamic> toJson()=>{...payload(),'step':step};
  void restore(Map<String,dynamic> j){step=j['step'] as int? ?? 0;currency=j['currency'] as String? ?? 'RUB';available=j['available_now'] as int? ?? 0;reserve=j['minimum_buffer'] as int? ?? 0;incomes.addAll((j['incomes'] as List<dynamic>? ?? []).map((e)=>IncomeDraft.fromJson(e as Map<String,dynamic>)));expenses.addAll((j['expenses'] as List<dynamic>? ?? []).map((e)=>ExpenseDraft.fromJson(e as Map<String,dynamic>)));debts.addAll((j['debts'] as List<dynamic>? ?? []).map((e)=>DebtDraft.fromJson(e as Map<String,dynamic>)));}
}
int? parseMoney(String value) { final normalized=value.replaceAll(RegExp(r'[ _]'),'').replaceAll(',','.'); final parsed=num.tryParse(normalized); if(parsed==null||parsed<0)return null; return (parsed*100).round(); }
