import {ApiErrorSchema,DebtSchema,ExplanationSchema,PlanSchema,TransactionSchema,type Debt,type Explanation,type Plan,type Transaction} from '../domain/models';
const base=(import.meta.env.VITE_API_BASE_URL as string|undefined)?.replace(/\/$/,''); let accessToken:string|undefined; let refreshPromise:Promise<boolean>|undefined;
export class AppError extends Error {constructor(public code:string,message:string,public status=0){super(message)}}
const messages:Record<number,string>={400:'Проверьте введённые данные',401:'Сессия завершена. Войдите снова',403:'Недостаточно прав',404:'Запись не найдена',409:'Данные изменились. Проверьте конфликт',422:'Проверьте поля формы',500:'Сервис временно недоступен'};
async function refresh(){if(refreshPromise)return refreshPromise; refreshPromise=(async()=>{const token=sessionStorage.getItem('vyhod_refresh');if(!token||!base)return false;const response=await fetch(`${base}/auth/refresh`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:token})});if(!response.ok)return false;const body=await response.json() as {access_token:string;refresh_token:string};accessToken=body.access_token;sessionStorage.setItem('vyhod_refresh',body.refresh_token);return true})().finally(()=>{refreshPromise=undefined});return refreshPromise}
export function mapError(status:number,raw:unknown){const parsed=ApiErrorSchema.safeParse(raw);return new AppError(parsed.success?parsed.data.error.code:`http_${status}`,parsed.success?parsed.data.error.message:(messages[status]??'Не удалось выполнить запрос'),status)}
async function request<T>(path:string,init:RequestInit={},retry=true):Promise<T>{if(!base)throw new AppError('config','VITE_API_BASE_URL не настроен');const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),10000);try{const response=await fetch(`${base}${path}`,{...init,signal:controller.signal,credentials:'include',headers:{'Content-Type':'application/json',...(accessToken?{Authorization:`Bearer ${accessToken}`}:{ }),...init.headers}});if(response.status===401&&retry&&await refresh())return request(path,init,false);const raw=response.status===204?undefined:await response.json().catch(()=>undefined);if(!response.ok)throw mapError(response.status,raw);return raw as T}catch(error){if(error instanceof AppError)throw error;if((error as Error).name==='AbortError')throw new AppError('timeout','Сервер не ответил вовремя');throw new AppError('network','Нет связи с сервером')}finally{clearTimeout(timeout)}}
function saveTokens(v:{access_token:string;refresh_token:string}){accessToken=v.access_token;/* Temporary compatibility adapter: refresh is session-only until backend supports HttpOnly cookies. */sessionStorage.setItem('vyhod_refresh',v.refresh_token)}
export const api={async auth(kind:'login'|'register',email:string,password:string){const result=await request<{access_token:string;refresh_token:string}>(`/auth/${kind}`,{method:'POST',body:JSON.stringify({email,password})});saveTokens(result)},async logout(){const token=sessionStorage.getItem('vyhod_refresh');if(token)await request('/auth/logout',{method:'POST',body:JSON.stringify({refresh_token:token})}).catch(()=>undefined);accessToken=undefined;sessionStorage.removeItem('vyhod_refresh')},async plan():Promise<Plan>{return PlanSchema.parse(await request('/plan'))},async explanation():Promise<Explanation>{return ExplanationSchema.parse(await request('/plan/explanation'))},async debts():Promise<Debt[]>{return DebtSchema.array().parse(await request('/debts'))},async transactions():Promise<Transaction[]>{const value=await request<unknown>('/transactions?limit=100');return TransactionSchema.array().parse((value as {items?:unknown}).items??value)},async mutate(path:string,method:string,payload:unknown,key:string){return request(path,{method,headers:{'Idempotency-Key':key},body:payload===undefined?undefined:JSON.stringify(payload)})}};
export const __testing={refresh,setAccess:(v?:string)=>{accessToken=v}};
